### ISSUE TITLE
Tracking issue for Beta

### ISSUE THREAD

**Issue by psschwei** [knative-sandbox/container-freezer#151]
Beta plan:

* [ ] https://github.com/knative-sandbox/container-freezer/issues/19
* [ ] Reducing resource usage of paused containers
* [ ] Don't probe paused containers
* [ ] Reduce permissions required to run the freezer

**Comment by psschwei** [comment]
> for `Don't probe paused containers`, it's done in serving?

Yes, I'm just tracking everything here (now that we have a repo) rather than over there
